### ISSUE TITLE
get methods can't work with generic types

### ISSUE THREAD

**Issue by grodin** [Gridstone/RxStore#14]
I should have spotted this one a while ago.

Since all the `get()`,  `getList()`, etc. methods take a `Class<T>` instead of a `Type`, it's not type-safe to use them with generic classes. If you want to try to get some `Foo<Bar>` back out you have to call the method with `Foo.class` and then cast from `Foo` to `Foo<Bar>`, which is not great.

The `Converter`s use `Type` so it should actually not be a problem to change all of those methods to take `Type`. Furthermore, it shouldn't be a breaking change since `Class<T>` implements `Type`. All existing code should just work.

What do you think?

**Comment by chris-horner** [comment]
Good spot! I'll make sure this gets into the next release.

**Comment by chris-horner** [comment]
This is actually a tricky one due to type erasure. If they take in a `Type` rather than a `Class<T>`, then the returned `Observable` will be `Observable<Object>`. T is lost.

In suggestions? I'm not sure how we can get around this one.

**Comment by grodin** [comment]
No good ideas, sorry. I don't think I thought about it properly when I raised the issue actually. Let's close it for now, and if I come with something I'll reopen it.
