### ISSUE TITLE
Check existence ?

### ISSUE THREAD

**Issue by benju69** [Gridstone/RxStore#16]
Great lib !
But I have a problem, How can I know if an object already exists in the RxStore ?

**Comment by chris-horner** [comment]
You can check if a particular store is empty by using RxJava's `isEmpty()`

```java
rxStore.get(key, Thing.class).isEmpty()
```

Do you think there would be much benefit in adding an explicit `hasValue()` method?

**Comment by benju69** [comment]
Ok thanks, isEmpty is good
Maybe, it's surely more explicit :)

**Comment by chris-horner** [comment]
Explicit is good, but I'm not sure we want to introduce methods that are just subtle variations of existing Rx methods. Closing for now.
