### ISSUE TITLE
Store in a zipfile

### ISSUE THREAD

**Issue by benju69** [Gridstone/RxStore#17]
I have and idea for Enhancement : store objects in a zip, to reduce size on phone

**Comment by chris-horner** [comment]
Any particular motivation to reduce files that are just a couple of KB? Is there really much of a gain? If you have a particular desire to have as small a footprint on the filesystem as possible, you could write a custom `Convertor` to take care of that.

**Comment by benju69** [comment]
Well in my case I have a lot of MB

**Comment by chris-horner** [comment]
I've been thinking about re-implementing `Convertor`s for a while now, as they're pretty inflexible in their current state. (I'd really like to support [Moshi](https://github.com/square/moshi)).

In making them more flexible, that would allow for easy implementation of `Convertor`s that can read and write from zipped streams. However, I'm not convinced this should be the default behaviour of any particular convertor. It's certainly something that could be provided in example code, but its requirement is niche enough that I don't want to include it in the main library.
