### ISSUE TITLE
Convertors should be more flexible.

### ISSUE THREAD

**Issue by chris-horner** [Gridstone/RxStore#18]
Right now it sucks working with a `Writer` and a `Reader`, making it very difficult to support [Moshi](https://github.com/square/moshi), or wrap files in GZip streams. Would be nice to come up with a more flexible solution.

**Comment by aphexcx** [comment]
Has anyone successfully written a moshi converter for this?

**Comment by chris-horner** [comment]
I've been experimenting with this in a few different internal projects. Here's one I've been playing around with in Kotlin with a hard dependency on Moshi: https://gist.github.com/chris-horner/223ad6fdc9f1a55d646b50ebff6f998c

At some point I'll be re-writing RxStore's converters to work correctly with Moshi (and many other things, as it should be flexible).

**Comment by chris-horner** [comment]
Converters now take in a `File` and are MUCH more flexible. There's also a provided `MoshiConverter` 😄
