### ISSUE TITLE
Possibility of corruption of store data on app termination

### ISSUE THREAD

**Issue by RomaneFerreira** [Gridstone/RxStore#20]
# Hello, I've been using this lib for some time now in my project. However, I found that my stores and data get corrupt at times. Upon examination, I found that data might be corrupted if the app is killed during the `converter.write` call, resulting in an incomplete write and so a corrupt file. This seems like a critical issue with this lib, IMHO could be solved by writing the data to a randomly named temporary file and then doing a rename-overrite to the key name so that at no point in time the store file is in an invalid state.

**Comment by chris-horner** [comment]
Totally agree! I'll jump on this next chance I get 😄

**Comment by chris-horner** [comment]
Fixed in #38
