### ISSUE TITLE
addToList is not thread safe

### ISSUE THREAD

**Issue by theangrydev** [Gridstone/RxStore#21]
Hopefully I am missing something here, but at first glance, it seems that addToList is not thread safe (race conditions can lead to lost updates).

I can see you have thought about write locks elsewhere (via the runInWriteLock method) but observeAddToList calls get() internally which uses a read lock.

Hopefully you have more insight into this, but it is a blocking issue for me.

**Comment by chris-horner** [comment]
`addToList()` calls through to `observeAddToList()`, which first calls `get()`, modifies the list, and then flatMaps to `observePut()`. `observePut()` runs inside of a write lock. I may have missed something, but I'm reasonably certain that should protect you from race conditions.

Are you able to create a small sample that reproduces your issue?

**Comment by theangrydev** [comment]
I'll have a go at a minimal example when I get some time, could be that I messed something up in my own code. Thanks for the quick response!

**Comment by theangrydev** [comment]
Ah yeah, think I might have spotted the cause. The  get() loads a copy of the list L1 in thread A. It adds the new value A in the map inside observeAddToList. Now thread B does the same thing, loads a copy of the list, also L1 and adds B in the map inside observeAddToList, before thread A has entered the write lock inside observePut. At this point one update is already guaranteed to be lost. I think you need both the read and the write of the list inside the write lock to avoid this issue

**Comment by chris-horner** [comment]
Nice detective work. I'll have a deeper look at this tomorrow morning AU time.

**Comment by chris-horner** [comment]
5.0.3 is up now on jcenter with the fix. Should sync to central shortly! Thanks very much for helping us find this bug, @theangrydev

**Comment by theangrydev** [comment]
No problem, thanks for the quick fix
