### ISSUE TITLE
Delete store when not needed.

### ISSUE THREAD

**Issue by lectricas** [Gridstone/RxStore#23]
Hi. I want to make some sort of cache with your lib. Rxcache just don't work with dagger2.
Is there any way to delete files after I don't need them anymore?

**Comment by chris-horner** [comment]
You can indeed delete files with `store.delete()`. [See here](https://github.com/Gridstone/RxStore/blob/master/rxstore/src/main/java/au/com/gridstone/rxstore/StoreProvider.java#L408).

Is this what you're referring to?
