### ISSUE TITLE
Android + Kotlin build error: Multiple dex files define Lorg/jetbrains/annotations/NotNull

### ISSUE THREAD

**Issue by panell** [Gridstone/RxStore#28]
If you create new Android project, configure Kotlin (add Kotlin dependencies) and add RxStore dependencies Android build will fail with Error:
_Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/jetbrains/annotations/NotNull;_

(make sure to run gradle _build_ task becouse with incremental compilation this may actually work sometimes )

This happens becouse both Kotlin and RxStore are adding the same dependency to the project _org.jetbrains.annotations_

Fix
`
compile ('au.com.gridstone.rxstore:rxstore:5.0.5') { exclude group: 'org.jetbrains'}
compile ('au.com.gridstone.rxstore:rxstore-kotlin:5.0.5') { exclude group: 'org.jetbrains'}
compile ('au.com.gridstone.rxstore:converter-moshi:5.0.5') { exclude group: 'org.jetbrains'}
`

For now this fix works, but I wondes can we make it work by default? (kind of making dependencies optional?)

**Comment by chris-horner** [comment]
Yeah, this is a really big issue. I was keen to add some nullability annotations to make interoperability with Koltin *easier*!

I'll need to do another hunt and find an alternative set of annotations we can use to mark nullability.

**Comment by panell** [comment]
Kotlin supports multiple types of 'nullable anotations' (if I remember correctly this list includes annotations from Android)
