### ISSUE TITLE
Create legacy rxjava (1) branch?

### ISSUE THREAD

**Issue by corcoran** [Gridstone/RxStore#43]
Would having a "latest version" for regular ol' RxJava users make sense?  I say this as someone who essentially has to run RxJava in a project and can't upgrade at the moment but still want to use this library as it was before the RxJava2 update.

**Comment by chris-horner** [comment]
There's nothing stopping you from targeting an earlier release. What benefit would there be in providing an alternate branch? You'd like the updated API but for RxJava1?

**Comment by corcoran** [comment]
I actually meant for others discovering this library for the first time. Of course they can target an older release but I meant more of if it would make sense to have it explicitly mentioned somewhere with a reference to the old API documentation.

**Comment by chris-horner** [comment]
Ahh, right right. I think the simplest solution would be to update the README with a link the repository at its previous tag.

**Comment by chris-horner** [comment]
Fixed in #44.
