### ISSUE TITLE
Model is converting into LinkedTreeMap

### ISSUE THREAD

**Issue by rahulr4** [Gridstone/RxStore#46]
Hello,
A Weird issue is coming up where a List of type X class is being converted into LinkedTreeMap when fetching from store.
`{
  "selectedFilters": {
    "LanguageFilter": [
      {
        "displayName": "German",
        "mChecked": true,
        "name": "German",
        "value": 3
      }
    ],
    "LocationRadius": 50,
    "SortOrder": [
      {
        "displayName": "By Distance",
        "mChecked": true,
        "name": "ByDistance",
        "value": 1
      }
    ]
  }
}

![image](https://user-images.githubusercontent.com/3830891/36541316-83167654-1803-11e8-9695-6e20ce8bf451.png)

The above screenshot will help. This is while fetching and when i am saving it in store, the actual model class is there`

**Comment by chris-horner** [comment]
Which `Converter` are you using? Could you please post the exact code of how you write to the store?

**Comment by chris-horner** [comment]
Closing for now, pending more information from the original reporter.
