### ISSUE TITLE
Building requires an internet connection

### ISSUE THREAD

**Issue by grodin** [Gridstone/RxStore#8]
Right now, when building this, you need an internet connection for the `apply from` line in `build.gradle` in the `grex` module. I understand what it's for, it's so you can publish to Maven Central, but it's a wee bit annoying when trying to work on the library with no/patchy internet, even though you've got all the dependencies locally cached.

I know of two ways of solving this:

1. Copy Chris Banes' gradle script into the repo, and use `apply from` with a relative path. I've seen this used in other projects but not done it myself.

2. Publish to jCenter, and let them push to Central. They have a gradle plugin which makes it all really easy. I've done part of this, the publishing to jCenter bit, but I didn't do the pushing to Central bit just because it's a bit of a faff to get set up on Maven Central.

Option 2 would be my preference, but it's not possible to do it via a PR since you'd want control of the Bintray repo and it needs your Maven Central password to do it. It's all actually really easy, since Bintray has good interfacing with GitHub, but it's up to you in the end.

**Comment by chris-horner** [comment]
I wasn't aware that it was so easy to let jCenter push to Central for you! I'll definitely look into this, as pushing to Central is a massive pain.

**Comment by chris-horner** [comment]
Implemented in 420354f57934b813b79b9c9cc70430e5bff2eca1.
