### ISSUE TITLE
Remove Roboelectric dependency?

### ISSUE THREAD

**Issue by grodin** [Gridstone/RxStore#9]
If #7 gets merged, then there isn't much point in the android tests any more. The android version of `GRexPersister` is an almost trivial extension of `BaseGRexPersister` and doesn't really need any tests.

Further, with the [new unit testing support][1], Roboelectric is not needed any more. The unit testing stuff is new, admittedly, so it may not be totally stable.

In any case, the `roboelectric-gradle-plugin` version needs bumping, because the current version is incompatible with v1.1 of the android gradle plugin(I have a feeling that gradle plugin incompatibility is going to be a major headache in the future...).

[1]:http://tools.android.com/tech-docs/unit-testing-support

**Comment by chris-horner** [comment]
Fixed in a216ffe02114ead53f89f9cfade23818e81e248b
